@Library('ci-jenkins-shared-libraries@main') _
def cipipeline = new opstree.ci.templates.java_ci.java_ci()

node {
  cipipeline.call([
    // WORKSPACE MANAGEMENT
    clean_workspace                  : true,

    // VCS MANAGEMENT
    repo_https_url                   : "https://github.com/opstree/OT-Microservices.git",
    repo_ssh_url                     : "https://github.com/opstree/OT-Microservices.git",
    repo_branch                      : params.BRANCH ?: "master",
    repo_url_type                    : "http",
    jenkins_git_creds_id             : "github-token",
    source_code_path                 : "/OT-Microservices/salary",

    // DEPENDENCY SCANNING — OFF
    dependency_check                          : 'false',
    fail_job_if_dependency_returned_exception : 'false',

    // CREDS SCANNING (GITLEAKS)
    gitleaks_check                   : true,
    fail_job_if_leak_detected        : false,
    gitleaks_report_format           : "json",
    gitleaks_report_jenkins_publish  : false,

    // BUILD ARTIFACT
    perform_code_build               : true,
    build_tool                       : 'maven',
    pom_location                     : '.',
    java_version                     : '17',
    codeartifact_dependency          : false,
    codeartifact_domain              : '',
    codeartifact_owner               : '',

    // UNIT TESTING
    unit_testing_check               : 'true',
    fail_job_if_unit_issue_detected  : 'false',
    unit_test_reports_path           : '**/target/surefire-reports/*.xml',

    // STATIC CODE ANALYSIS — OFF
    static_code_analysis_check              : false,
    fail_job_if_analysis_returned_exception : 'false',

    // BUILD DOCKERFILE
    perform_build_dockerfile         : false,
    dockerfile_location              : '/salary/Dockerfile',
    dockerfile_context               : '/salary',
    image_name                       : 'salary-service',
    image_tag                        : 'latest',

    // IMAGE SCANNING (TRIVY)
    image_scanning_check             : false,
    scan_severity                    : 'HIGH,CRITICAL',
    image_scanning_report_publish    : 'true',

    // IMAGE SIZE VALIDATOR
    image_size_validator_check       : false,
    max_allowed_image_size           : '500',
    fail_job_if_validation_fail      : 'false',

    // PUBLISH ARTIFACT — OFF
    artifact_publish_check           : false,

    // DEPLOYMENT — OFF
    enable_trigger_cd_pipeline       : false,

    // NOTIFICATION
    notification_enabled             : false
  ])
}
